// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkbkhihfgiwkqoptxyqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprYmtoaWhmZ2l3a3FvcHR4eXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTg0MTIsImV4cCI6MjA2MDk5NDQxMn0.jRRPp1QgnYqIPZoObizsqqvArvB7AZ9oh7BMeqk1JKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);